### ISSUE TITLE
TTN V3 Payload formatter fails when setting in TTN due to length > 40960

### ISSUE THREAD

**Issue by BookSwapSteve** [synetica/enlink-decoder#1]
When trying to use the Uplink Decoder, TTN gives the error message:

> Formatter code must have less than 40960 characters

For the file Synetica enLink ttn_V3 Uplink Decoder.js

It looks like there are 41,428 characters. Sadly removing the header only gets it down to 41,296

Found on The Things Stack Cloud Standard V3.29.1

**Comment by synetica** [comment]
Hi Steve! Thanks for finding this issue. I shall shrink the code size. I can't believe how it's grown over the years.
Thanks again!
David @ Synetica.

**Comment by synetica** [comment]
Removed the comments, and excess fluff. File size reduced to 36.5k
